version: "2.3"
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  workspace:
    #env_file:
    #  - .env
    #image: devrt/ros-devcontainer-vscode:melodic-desktop
    build: .
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3001:3000"
      - "3002:8888"
    volumes:
      - .:/workspace:cached
      - ~/.gitconfig:/home/developer/.gitconfig
    environment:
      - DISPLAY=:0
    volumes_from:
      - xserver
    depends_on:
      - xserver
